name: Publish Demo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Yarn and gh-pages
        run: |
          npm install -g yarn
          npm install -g gh-pages@3.0.0
      - name: Install Dependencies
        run: |
          npx lerna bootstrap
      - name: Build Website
        run: |
          yarn build:piral
          echo "my-coding-zone.samples.piral.cloud" > dist/release/CNAME
          cp dist/release/index.html dist/release/404.html
      - name: Publish Pilet
        run: |
          npx pilet publish 'packages/*-pilet' --fresh --url https://feed.piral.cloud/api/v1/pilet/my-coding-zone-sample --api-key $PIRAL_FEED_TOKEN
        env:
          PIRAL_FEED_TOKEN: ${{ secrets.PIRAL_FEED_TOKEN }}
      - name: Deploy Emulator
        run: |
          npm publish dist/emulator/*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Deploy Website
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          gh-pages -d "dist/release" -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
